//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospitool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bed
    {
        public int BedID { get; set; }
        public int PatientID { get; set; }
        public int ReceptionistID { get; set; }
        public string BedRentSDate { get; set; }
        public string BedRentEDate { get; set; }
        public System.DateTime BedRegDate { get; set; }
    }
}
