//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospitool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labworker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Labworker()
        {
            this.Labtests = new HashSet<Labtest>();
        }
    
        public int LabworkerID { get; set; }
        public string LabworkerName { get; set; }
        public string LabworkerSurname { get; set; }
        public string LabworkerTC { get; set; }
        public string LabworkerAddress1 { get; set; }
        public string LabworkerAddress2 { get; set; }
        public string LabworkerMobile1 { get; set; }
        public string LabworkerMobile2 { get; set; }
        public string LabworkerGender { get; set; }
        public int LabworkerAge { get; set; }
        public string LabworkerEmail { get; set; }
        public string LabworkerPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Labtest> Labtests { get; set; }
    }
}
