//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospitool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptionist
    {
        public int ReceptionistID { get; set; }
        public string ReceptionistName { get; set; }
        public string ReceptionistSurname { get; set; }
        public string ReceptionistTC { get; set; }
        public string ReceptionistAddress1 { get; set; }
        public string ReceptionistAddress2 { get; set; }
        public string ReceptionistMobile1 { get; set; }
        public string ReceptionistMobile2 { get; set; }
        public string ReceptionistGender { get; set; }
        public int ReceptionistAge { get; set; }
        public string ReceptionistEmail { get; set; }
        public string ReceptionistPassword { get; set; }
    }
}
